parameters:
#    comppi_description.example.class: Comppi\DescriptionBundle\Example

services:
#    comppi_description.example:
#        class: %comppi_description.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
