ComppiProteinSearchBundle:
    resource: "@ComppiProteinSearchBundle/Resources/config/routing.yml"
    prefix:   /protein_search/

ComppiDownloadDbBundle:
    resource: "@ComppiDownloadDbBundle/Resources/config/routing.yml"
    prefix:   /download/

ComppiDescriptionBundle:
    resource: "@ComppiDescriptionBundle/Resources/config/routing.yml"
    prefix:   /
    defaults: { _controller: DescriptionBundle:Description:About }

StatBundle:
    resource: "@StatBundle/Controller/"
    type:     annotation
    prefix:   /stat/

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
