ComppiDownloadDbBundle_download:
    pattern:  /
    defaults: { _controller: ComppiDownloadDbBundle:DownloadDb:download }

ComppiDownloadDbBundle_serve:
    pattern:  /serve
    defaults: { _controller: ComppiDownloadDbBundle:DownloadDb:serve }